ros2-devel: user configurable publish rate
swri-robotics/gps_umd pull request #58
Opened 2022-06-17 18:17 UTC by packwidth

This PR adds the ability to control the publish rate through the `ros2 param` facility or through a config file. A demo launch file demonstrates the use of the config file. Addresses #55

2022-06-20 14:18 UTC, danthony06 requested changes

2022-06-20 16:59 UTC, packwidth commented on gpsd_client/launch/gpsd_client-launch.py
> +# Copyright 2019 Open Source Robotics Foundation, Inc.
Got it. Resolved. I was wondering who was maintaining this. Thanks!

2022-06-21 18:59 UTC, danthony06 approved these changes

2022-06-21 19:00 UTC, merged

2022-06-21 19:00 UTC, danthony06 commented
Thanks! I'll try to get a release out by the end of the day tomorrow.